C_SRC       = lex.c expr.c error.c decl.c stmt.c main.c
H_SRC			= lex.h expr.h error.h decl.h stmt.h tokens.txt
#OBJS        = $(C_SRC:.c=.o)
CC          = ucc


all:  $(C_SRC) $(H_SRC)
	$(CC) -o sc.exe $(C_SRC)
	type demo.c
	sc.exe < demo.c
clean:
	del *.obj sc.exe
